# action.yml
name: 'upload-actions'
description: 'upload actions'
inputs:
  signUrl:
    description: 'sign url'
    required: true
  mimeType:
    description: 'mimeType'
    required: true
  st:
    description: 'st'
    required: true
  filePath:
    description: 'file path'
    required: true
  title:
    description: 'file title'
    required: false
outputs:
  resId:
    description: 'resId'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - -signUrl
    - ${{ inputs.signUrl }}
    - -mimeType
    - ${{ inputs.mimeType }}
    - -st
    - ${{ inputs.st }}
    - -filePath
    - ${{ inputs.filePath }}
    - -title
    - ${{ inputs.title }}